export enum ConfigKeys {
    API_PORT = "API_PORT",
    NODE_ENV = "NODE_ENV",
    ENABLED_ACCOUNTS = "ENABLED_ACCOUNTS",
    TORRENT_MAX_IDLE_TIME_MS = "TORRENT_MAX_IDLE_TIME_MS",
    TEMP_FOLDER_LOCATION = "TEMP_FOLDER_LOCATION",
    SPEED_LIMIT_ENABLED = "SPEED_LIMIT_ENABLED",
    SPEED_LIMIT_BYTES_PER_SECOND = "SPEED_LIMIT_BYTES_PER_SECOND",
}